import React from 'react';
import { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ThemeProvider } from 'next-themes';
import { Layout } from './components/Layout';
const inter = Inter({ subsets: ['latin'] });

import './globals.css';

//Note: Generate default data by this way
export const metadata: Metadata = {
  title: 'Home',
  description: 'Generated by create next app',
  generator: 'Next.js',
  applicationName: 'Next.js',
  referrer: 'origin-when-cross-origin',
  keywords: ['Next.js', 'React', 'JavaScript'],
  creator: 'Thang Nguyen',
  formatDetection: {
    email: false,
    address: false,
    telephone: false,
  },
  themeColor: '#ffffff',
  robots: 'max-image-preview:large',
  icons: [
    {
      rel: "icon",
      url: "favicon.ico",
      sizes: "32x32"
    },
    {
      rel: "icon",
      url: "favicon.ico",
      sizes: "16x16"
    },
    {
      rel: "apple-touch-icon",
      url: "favicon.ico",
      apple: "favicon.ico",
      sizes: "180x180"
    }
  ],
  openGraph: {
    locale: 'en_US',
    type: 'website',
    url: 'https://kyberosc.com/',
    title: 'My Website',
    description: 'KyberOSC – Qualitative software development',
    siteName: "KyberOSC",
    images: [
      {
        url: "https://prod-kyber-wp-website.s3.ap-southeast-1.amazonaws.com/wp-content/uploads/2021/12/21080831/logo_kyberosc.png",
        height: 630,
        width: 1200,
      }
    ],
  },
  twitter: {
    card: "summary",
    title: "KyberOSC – Qualitative software development",
    description: "KyberOSC – Qualitative software development",
    site: "https://kyberosc.com/",
    images: "https://prod-kyber-wp-website.s3.ap-southeast-1.amazonaws.com/wp-content/uploads/2021/12/21080831/logo_kyberosc.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <ThemeProvider attribute="class">
          <Layout>
            {children}
          </Layout>
        </ThemeProvider>
      </body>
    </html>
  );
}
